
name = "partner-request-portal"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"

[site]
bucket = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "partner-portal-db"
database_id = "69360925-a7d1-403b-b869-ed8ca8a34ef6"

[env.production]
ZAPIER_WEBHOOK_URL = "your-zapier-webhook-url-here"

[env.development]
ZAPIER_WEBHOOK_URL = "your-zapier-webhook-url-here"

